# Generated by Django 5.1.2 on 2024-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking_ticket_id_booking_ticket_is_scanned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endTime',
        ),
    ]
