# Generated by Django 5.1.2 on 2024-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
